### ISSUE TITLE
关于最新版通用脚本鱼翅厨师报错

### ISSUE THREAD

**Issue by sanqianjun** [hzqst/CGAssistantJS#7]
大佬你好。今天终于能做鱼翅了。可是最新版本的通用脚本鱼翅厨师会报登录点错误，我在QQ群也有反应。
我换成旧版本就可以正常使用不报错。我用的是20210502那个版本。

**Comment by sanqianjun** [comment]
希望大佬查证，再次感谢!

**Comment by sanqianjun** [comment]
不好意思，说错了，旧版本用的是20210722那个

**Comment by sanqianjun** [comment]
我又来了！大佬，最新版本通用脚本‘鱼翅哥拉尔’会报CGAssistantJS-master\cgaapi.js:219
				throw new Error('异步登出无反应，可能网络不稳定或者已经掉线！');
				^

Error: 异步登出无反应，可能网络不稳定或者已经掉线！
    at C:\Users\Administrator\Desktop\CGAssistantJS-master\cgaapi.js:219:11
    at C:\Users\Administrator\Desktop\CGAssistantJS-master\cgaapi.js:4177:14
